### PR TITLE
Add a story to the  Backlog in Readme

### PR DESCRIPTION
**Pull request by Abdelmouise**
The current model, gives a number of people per household that does not exceed 5 with a mean  around 3.5 (by construction), we can refine this model using the data from the General Census of Population of the Moroccan government

### CODE REVIEW

**Comment by AshtonIzmev** [comment]
Thanks. Someone suggested the same feature using a distribution with those parameters : N(mu=4.52 , sigma^2=4.71). 
I thought it would be nice (because it can have a lot of influence on the pandemic) to have this but it seemed like a bit complicated feature to implement because of the was the loop is done. You got this ?

**Comment by Abdelmouise** [comment]
sorry but I did not quite understand what you mean, I thought it would be enough to change the body of the function "build_individual_houses_map" in core, even the function signature remains the same.
In the end it is not that simple? there are some complicated dependencies?

**Comment by AshtonIzmev** [comment]
No you're right, it should be done only working in 
`build_individual_houses_map(number_individual_arg, proba_same_house_rate)`
and getting rid of the very ugly proba_same_house. Maybe for a second phase, the impact could be on:
`build_individual_adult_map(individual_house_map_arg)`

**Comment by Abdelmouise** [comment]
I did not like it either this "proba_same_house_rate"

**Comment by AshtonIzmev** [comment]
> N(mu=4.52 , sigma^2=4.71)

Forgot to say but this gaussian modelization of the moroccan family household is from Mohamed Semlali and he said it fits HCP data very well.

**Pull request merged**
