### PR TITLE
Add plot R0

### PR DESCRIPTION
**Pull request by Abdelmouise**
I added R0 plot in a linear scale 
I'm not sure about the R0 formula , I calculated with the ratio of new infections by the number of infected people.
infected  = infected+hospitalized+isolated

### CODE REVIEW

**Comment by Abdelmouise** [comment]
I added a correction on R0 formula, because it wasn't correct to consider the new infected cases in dominator. Maybe we need to add a polynomial filter to smooth the curve

**Comment by AshtonIzmev** [comment]
Merged. Thanks !

**Comment by AshtonIzmev** [comment]
Just checked the formula, I do not agree with that. For me R0 is new_cases / contagious people. Which is how many people got infected by contagious people.
if 1 person newly infected and 1 person contagious => R0 = 1
if 10 newly infected and 100 persons contagious => R0 = 0.1 since each contagious infected 0.1 person. And added a 1+ to avoid 0 condition.

Tell me if my understanding is not correct

**Comment by Abdelmouise** [comment]
Your understanding is completely correct, but that's what I put in the code (I suppose)
I look at the number of new infected cases in D-day and I divid it by the number of contagious cases in D-1 which gives the number of people infected on day D by the number of contagious people.


and, contagious= infected+hospitlized+isolated

you are right about the dominator,  (I thought that the number of starting cases is not zero, but I forgot that at the end of the epidemic it could be the case )

**Comment by Abdelmouise** [comment]
Ok i see, we have juste   different definitions of contagious people, I did not take into account the incubation period, but i think that is the correct definition.
Take for example the case of a disease with a very long incubation period, and suppose that on D-Day you have 100 non-contagious infected people and 10 contagious infected people. and these 10 contagious people will contaminate 20 new people

for you R0=20/10=2
and for me R0=20/110=0.18

but the curve of new infected will correspond to a curve with a slow evolution  at D-day(which means a small R0 number ) and maybe after the curve will be increased exceptionally. 

in the definition of wikipedia they say just infected (but I don't know if it means contagious)
i think  that the incubation period must also be represented somehow by R0

**Comment by AshtonIzmev** [comment]
Yep, the wikipedia definition was not clear, I had to look for more google results. 
But we agree. 

I created a get_contagious_people function and used it and then refactored some propagate code that used is_contagious (which did not smell right, or maybe I am over refactoring ^^). Code should be stable. I'll finish the article and add a few more scenarios and unit tests (if no bug found).

**Comment by Abdelmouise** [comment]
Cool, I can't wait to read the new article :)

**Comment by AshtonIzmev** [comment]
Implemented R0 definition is not good. I'll open a ticket

**Pull request merged**
