### PR TITLE
Add test isolation strategy

### PR DESCRIPTION
**Pull request by Abdelmouise**
Hi Issam,

the feature that I implemented is a little different than what you said the last time.
the strategy here is for each person hospitalized, the test will not be done randomly, but first we will target the family of the hospitalized person, then the positive family member he will be isolated. So I added another state"isolated" to the state dictionary, this state will be just another form of the infected state, but it will allow us to isolate these people so as not to go to work or stores.
I updates also the plots so we can see the amount of isolated persons.

we can also activate this strategy when we want(we could imagine that the government will proceed with this strategy after day "d" of confinement).

I think this approach makes sense, because it is the most likely scenario if the government has a limited number of tests. Add to that there is no tracking solution to identify contact with a sick person(except north korea ,Japon...).

Finally, we can add a random test scenario for people who were in contact with an infected person.

the current solution works but I have not yet added tests and I have not also modified all the scenarios. I let you see the changes and tell me what you think.

### CODE REVIEW

**Comment by AshtonIzmev** [comment]
Ok nice, let me check this conflict since it is the first big feature on the SEIR model and then merge.

**Comment by AshtonIzmev** [comment]
I merged the pull. Can you use the pycharm default code syntax recommendations ? (for example two newlines between function and stuff like this, space after "," etc).
Since there is a new state, it is a big change. Please be sure to add additionnal tests for increment_pandemic_1_day function (especially in transitions).

I think "update_isolation_state(old_virus_dic,new_virus_dic,env_dic)" is not a good idea because we used references for all the dics. It does not seem a good strategy to start duplicating them and having old and new virus dics. Track the newly hospitalized people in another way I think it will be better following the code spirit. Hope this helps.

**Comment by AshtonIzmev** [comment]
The update_isolation_state(old_virus_dic,virus_dic,env_dic) should be in increment pandemic state function, following the logic. All state transition should be located in one main place, and activated by some number (for example like the immune transition). Seems for me a bit more logical

**Comment by Abdelmouise** [comment]
Thank you Issam for your recommendation, I implemented the idea in the simplest way without following too much the code structure , that's why I asked to add another branch.
 I will work now on refactoring and optimization so that all the code will be in the same logic

**Comment by Abdelmouise** [comment]
I'm not using Pycharm IDE. I was just too lazy to install it on my personal computer, but i will do it now

**Pull request merged**
